### PR TITLE
add development server; run it using plackup

### PR DESCRIPTION
**Pull request by szabgab**

### CODE REVIEW

**Comment by davorg** [comment]
I wonder if this is overkill for a static site. I've been using App::HTTPThis for testing.

**Comment by szabgab** [comment]
Probably. I did not know that module. Now that I try it I can see it does not automatically show the index.html when I access a directory, does it to you?

**Comment by davorg** [comment]
No. It doesn't. I keep meaning to get round to submitting a patch to fix that.

**Comment by szabgab** [comment]
Maybe @melo will want to give a hand

**Comment by davorg** [comment]
See https://github.com/melo/app-htttpthis/pull/3

**Pull request closed without merging**
