### PR TITLE
allow authors to set default sort order on their pages

### PR DESCRIPTION
**Pull request by szabgab**

### CODE REVIEW

**Comment by davorg** [comment]
Looks good. Thanks.

**Comment by davorg** [comment]
Sorry, pressed the wrong button :-/

**Comment by davorg** [comment]
Am I missing something? It doesn't seem to work.

**Comment by szabgab** [comment]
It seems to work, my page https://cpandashboard.com/SZABGAB/ comes up sorted by date, most recent first, other pages show up sorted ABC

**Comment by davorg** [comment]
Oh. Yes, it does. It was probably a caching issue that I was seeing. Thanks for the patch.

**Comment by szabgab** [comment]
Thanks for accepting it so quickly.

**Pull request merged**
